apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fxql
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fxql
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fxql
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fxql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fxql
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vjjm-tenant/rhtap-demo-app/hacbs-test-project-fxql@sha256:81fc9f65c40d1049b261af209e9626f431c8d2f9d4f3b27160ca57381ce57ea3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
